[project]
name = "umich-consumer-sentiment"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "psutil>=5.9.0",
 "boto3",
 "httpx",
 "pyarrow",
 "deltalake>=0.17.0",
 "ratelimit",
 "tenacity",
]
